### ISSUE TITLE
[NPC][Mechanic] Bloodwarder Falconer - Going into Melee

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#459]
https://www.wowhead.com/npc=17994/bloodwarder-falconer#abilities

It can do multi shot and it has hunter abilities but it goes into melee instead.

**Comment by tonine-entro** [comment]
[CONFIRMED]
Tested on normal all spells work other than multi-shot.

**Comment by Bart748** [comment]
Added Ability Multishot to Bloodwarder Falconer

**Comment by MihawkEntropius** [comment]
https://streamable.com/ivouh6 

He moves into melee range on pull.

**Comment by tonine-entro** [comment]
NPC casts multishot. Can't find anywhere why they should not come into melee.

**Comment by Megalomaniac6** [comment]
Generally, mobs that have a ranged attack won't ever go into melee unless you go into their melee range. That's how most ranged casters, shooters, hunters or bomb flingers should work. There are occasions where they still continue casting the spell until they're oom instead of swapping to melee attacks.

**Comment by tonine-entro** [comment]
Opening the issue as NPC should be range attacking

**Comment by Bart748** [comment]
Should be fixed how, added range flags
