### ISSUE TITLE
[NPC][Ability] Eversong Woods 

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#494]
https://www.wowhead.com/npc=15273/arcane-wraith#abilities
It uses arcane bolt but very rarely, it should constantly cast it as long as it has mana, instead it hits melee for 10~ times and then cast 1 arcane bolt. Iirc thats wrong and it seems odd.

https://www.wowhead.com/npc=15636/eversong-green-keeper#abilities and https://www.wowhead.com/npc=15635/eversong-tender#abilities
missing rejuvenation , didn't find it on tbcdb but this should be it : https://www.wow-freakz.com/spells.php?spell=12160&name=rejuvenation   https://www.wowdb.com/spells/12160-rejuvenation

https://www.wowhead.com/npc=15668/grimscale-murloc#abilities
These murlocs dont cast fear on player, they cast on themself. 

https://www.wowhead.com/npc=15669/grimscale-oracle#abilities
https://www.wowhead.com/npc=15950/grimscale-seer#abilities
Missing https://www.wowhead.com/spell=26661/fear

https://tbcdb.com/?npc=15648#abilities
Not using mana residue

https://www.wowhead.com/npc=15274/mana-wyrm#abilities
not using https://www.wowhead.com/spell=25602/faerie-fire

**Comment by Nextcalibur** [comment]
Fixed Arcane Wraith.

**Comment by Bart748** [comment]
Updated Arcane Wraith's Arcane Bolt to main spell (set rangedflag true)
Added Ability rejuvenation to Eversong Green Keeper and Eversong tender
Changed Murlock's fear cast target to 1 = TARGET_T_HOSTILE instead of 5 = TARGET_T_HOSTILE_RANDOM_NOT_TOP
Added Ability Fear to Grimscale Oracle
Added Ability Fear to Grimscale Seer
"Not using mana residue", uses Mana Residue on death.
Added ability Faerie Fire to Mana Wyrm
