### ISSUE TITLE
[NPC] [Abilitys] [STV]

### ISSUE THREAD

**Issue by Bossyo** [Nextcalibur/Bugtracker#523]
https://classic.wowhead.com/npc=1557/elder-mistvale-gorilla#abilities **#Entry 1557**

https://classic.wowhead.com/npc=1907/naga-explorer#abilities **#Entry 1907**

https://classic.wowhead.com/npc=687/jungle-stalker#abilities **#Entry 687**

https://classic.wowhead.com/npc=730/tethis#abilities **#Entry 730**

https://classic.wowhead.com/npc=1565/bloodsail-sea-dog#abilities **#Entry 1565**

https://classic.wowhead.com/spell=15571/dazed **#Entry 1561**
https://classic.wowhead.com/spell=5101/dazed **#Entry 1561**

https://classic.wowhead.com/npc=2544/southern-sand-crawler#abilities **#Entry 2544**

https://classic.wowhead.com/spell=13496/dazed **#Entry 1563**

https://classic.wowhead.com/spell=1604/dazed **#Entry 1562**
https://classic.wowhead.com/spell=5101/dazed **#Entry 1562**

https://classic.wowhead.com/npc=1491/zanzil-naga#abilities **#Entry 1491**

https://classic.wowhead.com/npc=1490/zanzil-witch-doctor#abilities:0+1+17+2 **#Entry 1490**

https://classic.wowhead.com/npc=2534/zanzil-the-outcast#abilities **#Entry 1489**

https://classic.wowhead.com/npc=2537/chucky-ten-thumbs#abilities **#Entry 2537**

https://classic.wowhead.com/npc=1713/elder-shadowmaw-panther#abilities:mode=normal:50+1+18+3 **#Entry 1713**

https://classic.wowhead.com/npc=690/cold-eye-basilisk#abilities **#Entry 690**

https://classic.wowhead.com/npc=854/young-jungle-stalker#abilities **#Entry 854**

https://classic.wowhead.com/spell=1151/dash **#Entry 731**

https://classic.wowhead.com/npc=674/venture-co-strip-miner#abilities **#Entry 674**

https://classic.wowhead.com/npc=676/venture-co-surveyor#abilities **#Entry 676**

https://classic.wowhead.com/npc=677/venture-co-tinkerer#abilities **#Entry 677**

https://classic.wowhead.com/npc=783/skullsplitter-berserker#abilities **#Entry 783**

https://classic.wowhead.com/npc=782/skullsplitter-scout#abilities **#Entry 782**

https://classic.wowhead.com/npc=669/skullsplitter-hunter#abilities **#Entry 669**

https://classic.wowhead.com/npc=756/skullsplitter-panther#abilities **#Entry 756**

https://classic.wowhead.com/npc=670/skullsplitter-witch-doctor#abilities **#Entry 670**

https://classic.wowhead.com/npc=667/skullsplitter-warrior#abilities **#Entry 667**

https://classic.wowhead.com/npc=1114/jungle-thunderer#abilities **#Entry 1114**

https://classic.wowhead.com/npc=696/skullsplitter-axe-thrower#abilities **#Entry 696**

https://classic.wowhead.com/npc=780/skullsplitter-mystic#abilities:0+1+17+2 **#Entry 780**

https://classic.wowhead.com/npc=709/moshogg-warmonger#abilities **#Entry 709**

https://classic.wowhead.com/npc=679/moshogg-shaman#abilities **#Entry 679**

https://classic.wowhead.com/npc=710/moshogg-spellcrafter#abilities **#Entry 710**

https://classic.wowhead.com/npc=680/moshogg-lord#abilities #**Entry 680**

https://classic.wowhead.com/npc=678/moshogg-mauler#abilities **#Entry 678**

https://de.classic.wowhead.com/npc=818/maizoth#abilities **#Entry 818**

https://classic.wowhead.com/npc=4260/venture-co-shredder#abilities **#Entry 4260**

https://classic.wowhead.com/npc=682/stranglethorn-tiger#abilities:mode=40player:50+1+18+3 **#Entry 682**

https://classic.wowhead.com/npc=937/kurzen-jungle-fighter#abilities **#Entry 937**

https://classic.wowhead.com/npc=976/kurzen-war-tiger#abilities:50+1+17+2 **#Entry 976**

https://classic.wowhead.com/npc=938/kurzen-commando#abilities **#Entry 938**

https://classic.wowhead.com/npc=683/young-panther#abilities:mode=normal:50+1+18+3 **#Entry 683**

https://classic.wowhead.com/npc=1150/river-crocolisk#abilities #Entry 1150

https://classic.wowhead.com/npc=681/young-stranglethorn-tiger#abilities:mode=normal:50+1+18+3 **#Entry 681**

https://classic.wowhead.com/npc=701/bloodscalp-mystic#abilities **#Entry 701**

https://classic.wowhead.com/npc=11355/gurubashi-warrior#abilities **#Entry 11355**

https://classic.wowhead.com/npc=11346/hakkari-oracle#abilities **#Entry 11346**

https://classic.wowhead.com/npc=11383/high-priestess-haiwatna#abilities **#Entry 11383**

https://classic.wowhead.com/npc=1559/king-mukla#abilities **#Entry 1559**

https://classic.wowhead.com/npc=4505/bloodsail-deckhand#abilities **#Entry 4505**

https://classic.wowhead.com/npc=4506/bloodsail-swabby#abilities **#Entry 4506**

https://classic.wowhead.com/npc=1565/bloodsail-sea-dog#abilities **#Entry 1565**

**Comment by Bart748** [comment]
1557 does not have any abilities. The abilities listed are hunter spells.
1907 should cast Rend: 85% chance, 3-8s after combat started, 20-23s repeat.
687 does not have any abilities. Daze happens when he hits your back
Tethis: Rendon Rip added
1565 Should cast all his abilities
1561 Should have all his abilities
2544 Daze is a core mechanic
Bloodsail Swashbuckler: Kick Added
1562 Should cast all abilities
Zanzil Naga: Pummel, Hamstring added.
Zanzil Witch Doctor: Curse of Weakness and Shadowbolt added
Zanzil Hunter: Throw added
2537 no abilities
1713 no abilities
690 should use Crystalized Slumber
854 no abilities
731 should summon panthers at 50% hp 
Venture Co. Strip Miner: Dynomite added.
676 no abilities
Venture Co. Tinkerer: Fireball, Frost armor and Compact Harvest Reaper added
783 should use Head Crack (85% chance), 5-8s after combat, 14-20 repeat, random target
Skullsplitter Scout: Head Crack added.
Skullsplitter Hunter: Head Crack, Skullsplitter Pet and Trash added.
756 No abilities
Skullsplitter Witch Doctor: Healing Ward, Earthgrab Totem added
Skullsplitter Warrior: Head Crack, Shield Bash added
1114 no abilities
696 Should use all his abilities
780 Should use all his abilities
Mosh'Ogg Warmonger: Thunderclap Added
Mosh'Ogg Shaman: Bloodlust, Healing Ward and Chain Lightning added.
Mosh'Ogg Spellcrafter: Fireball and Flamestrike added.
Mosh'Ogg Lord: Intimidation and Battle Shout added.
Mosh'Ogg Mauler: Knockdown added.
Mai'Zoth: Frost Armor, Frostbolt, Frostbolt Volley, Flame Spike added
4260 no abilities
682 no abilities
937 no abilities
976 no abilities
Kurzen Commando, changed Events:
    Smoke bomb: 75%-30% health
    Smoke bomb + stealth + flee @30% hp
    Backstab when facing back
    Stealth: on Spawn and Out of Combat
683 no abilities
1150 Should cast Tendon Rip: 85%, 4-12s, 24-32s, on Target
681 no abilities
701 Should cast all abilities
11355 no abilities
Hakkari Oracle: Healing Wave, Earth Shock, Chain Lightning added.
High Priestess Hai'watna: Heal, Hex and Shadow Bolt Volley
1559 should cast abilities
Bloodsail Swabby: kick added.
1565 Should cast all.

Not the best rapport, took me about 2 hours as well.
Please for the future check multiple sources before adding every NPC in a zone to the List.

**Comment by MihawkEntropius** [comment]
1907 - **Not using it, to be tested as player toon further.**
Tethis - Working
1565 - **Poison working , gouge and backstab need to test on player toon.**
1561 - Working
Bloodsail Swashbuckler -Working
1562 - Working
Zanzil Naga - Working
Zanzil Witch Doctor - **Shadow Bolt not being cast**
Zanzil Hunter - **He is just staring at me.**
Cold Eye Basilisk - **Not using it, to be tested as player toon further.**
731 - Working
Venture Co. Strip Miner - **Not using it, to be tested as player toon further.**
Venture Co. Tinkerer - Working
783 - Working
Skullsplitter Scout - Working
Skullsplitter Witch Doctor - Working
Skullsplitter Warrior - Working
Skullsplitter Axe Thrower - Working
Skullsplitter Mystic - Working
Mosh'Ogg Warmonger - Working
Mosh'Ogg Shaman - **Healing Ward not working, rest worked.**
Mosh'Ogg Spellcrafter - Working
Mosh'Ogg Lord - Working
Mosh'Ogg Mauler - Working
Mai'Zoth - **Abilities working but running into melee instead of casting from distance.**
Kurzen Commando - **Backstab to be checked as player , rest working**
1150 - Working 
Bloodscalp Mystic - Working
Hakkari Oracle - Working
High Priestess Hai'watna - Working
1559 - **Intimidation to be checked further with player toon.**
Bloodsail Swabby - Working
