### ISSUE TITLE
[PVP][Mechanic] Travel time / Delay on spells.

### ISSUE THREAD

**Issue by KroqGar** [Nextcalibur/Bugtracker#541]
https://streamable.com/7k55af
https://streamable.com/y1rkv7

On these videos you can see both warrior and druid spamming their charge. What should happen is that they cross each other due to travel time of the spell , making them not cc each other right away and just swapping places.

What Happens on Entropius is that there is not such thing as travel time/delay and druid or warrior only gets the charge.

https://youtu.be/OftXYR06wY4?t=68
on this video rogue can shadowstep at the same time as warrior charge due to the stun not being instant.

**Comment by Nextcalibur** [comment]
Would require spell batching.

**Comment by Synful-Syn** [comment]
This is not spell batching, the warrior's stun is applied to the rogue once he's done moving to the location of it's target from its Charge.

**Comment by Nextcalibur** [comment]
In order for you to be able to counter a CC on cast you need to be able to get your counter into the same execution cycle. Unless you can time the spell casts down to the miliseconds, you will not get the intended behavior. In order for both spells to be added to the stack, executed and applied at the same time they need to be batched. 

Since charge has Effect[3] as Trigger Spell 7922 with delay 0 the stun will be cast when you charge, this is the data in the DBC files from Blizzard. 

If you want two players to stun eachother with the same CC spell both spells either needs to be cast with < 1ms delay or you need a system that puts recent spells together into something like a batch.

**Comment by Nextcalibur** [comment]
The last video linked in this issue shows spells being batched allowing both to resolve at the same time.
