### ISSUE TITLE
[NPC][Quest] Skar'this the Heretic - The Cudgel of Kar'desh

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#591]
https://wowwiki.fandom.com/wiki/Skar%27this_the_Heretic

https://tbc-twinhead.twinstar.cz/?quest=10901  from https://tbc-twinhead.twinstar.cz/?npc=22421

The quest is not obtainable from the npc. You cant talk to it.

**Comment by Nextcalibur** [comment]
Ok folks.. Let me bring some reality checks for everyone who takes this quest truly understands the lore/insight on how truly long it is and how the "Entire" chain begins and ends. I noticed the link and some though GREAT input on the chains but there not the entire chains accordingly. They leave out where its supposed to be picked up, and in truth most of the time you "cannot" pick up the quest due to not doing the prior quest chains so if your on this quest below is what you may want to do or of course quit at any moment. But the story doesn't end here clearly.

Quest chain 1 (8 Parts) : (this one of course)
Horde: The Hand of Gul'dan
Alliance: The Hand of Gul'dan
Enraged Spirits of Fire and Earth
Enraged Spirits of Water
Enraged Spirits of Air
Oronok Torn-heart
I Was A Lot Of Things...
A Lesson Learned
The Cipher of Damnation - Truth and History

Then as mentioned before there are the 3 quest in any order but MUST be completed in order to proceed to the next chain

- These are the Fragment of Damnation Quest Series (3 Parts Totalling 16 Quest + 1 Final but not end of Chain = 17 Quest in all):
(Part 1)
Grom'tor, Son of Oronok
The Cipher of Damnation - Grom'tor's Charge
The Cipher of Damnation - The First Fragment Recovered
(Part 2)
Ar'tor, Son of Oronok
Demonic Crystal Prisons
- The NPC ghost will appear - The chain continues:
Lohn'goron, Bow of the Torn-heart
The Cipher of Damnation - Ar'tor's Charge
The Cipher of Damnation - The Second Fragment Recovered
(Part 3)
Borak, Son of Oronok
Of Thistleheads and Eggs...
The Bundle of Bloodthistle
To Catch A Thistlehead
The Shadowmoon Shuffle
What Illidan Wants, Illidan Gets...
The Cipher of Damnation - Borak's Charge
The Cipher of Damnation - The Third Fragment Recovered

Now mind you "MUST" complete the above 3 Parts & also turn them into Oronok before carrying forward.

1 Quest
The Cipher of Damnation

Now also as mentioned before you will get a letter in the mail from
Khadgar to go to Shattrath and speak with A'Dal.

This has unlocked your future chains not mentioned linking them together is what I think people should understand the can of worms your about to open:

(4 Part Chain)
4 Trials total however only 3 can be accepted at first. They are 3 seperate quest given all at once so you can carry all 3 and complete and run back to turn in all together. The 4th is after the original 3 are completed.
The first 3 are:
Trial of the Naaru: Tenacity (HEROIC MODE) - Arcatraz of Tempest Keep. - Note: Here your saving the mage who will be friendly but you kill this boss: Harbinger Skyriss
Trial of the Naaru: Strength (HEROIC MODE) - Warlord Kalithresh (Steamvault) & Murmur (Shadow Labyrinth) in any order but both in Heroic Modes.
Trial of the Naaru: Mercy (HEROIC MODE) - Shattered Hand Executioner (Shattered Halls of Hellfire Citadel)

Now before we get to the fourth part do note after completing the initial 3 there is a mini chain the unlocks and continues on. You can have both the 4th trial and this chain at the same time:

Trial of the Naaru: Magtheridon (Raid) - Magtheridon

(2 Part Chain)
The Mark of Vashj - You talk to: Skar'this the Heretic (He is only found in Heroic Mode and is after the first boss) in The Slave Pens (Heroic Mode)
The Cudgel of Kar'desh
- Gruul the Dragonkiller (Gruul's Lair) & Nightbane (Karazhan)
Do note they can be completed in any order for the 2 dungeons on the last part of this quest chain.

That is all folks.

Quest Grand Total: 31
Heroic Dungeons: 5 (Slave Pens twice so technically 6)
Gold rewards/Items/Reputation and Experience gained I didn't do the math on sorry.
Normal Difficulty Dungeons: 0
