### ISSUE TITLE
[Quest] Sabotage the Warp-Gate!

### ISSUE THREAD

**Issue by SFCDaniel** [Nextcalibur/Bugtracker#614]
https://www.wowhead.com/quest=10310/sabotage-the-warp-gate
The Number of Demon spawns at the second Pylon is to high, seemed to spawn 5+ Demons but it should be only 3.

https://de.wowhead.com/quest=10310/sabotage-am-warptor#english-comments
"Solo'd as a lvl 70 enhancement shaman. some decent greens, 8500 health, 6800 mana - duel wield
1. first wave... as soon as you start to fight the lvl 68 guy, throw your Fire Elemental totem.. the fire guy will help you fight the 9 little demons. they are lvl 68, don't hit all that hard. there is a 2 min cooldown before you can throw your Earth elemental, so timing is crucial.

Heal a little bit you have a couple seconds..

2. second pylon, attack the lvl 68 guy, and then after you kill him the 3 demons come, throw your Earth elemental totem... he wont be able to help you all the way through cause these guys hit a little harder.. but he will buy enough time for you to get yourself a more even fight. then kill them.

3. last pylon, kill the 2 lvl 68s. the demon comes right after, fight him. hes a pushover."

**Comment by MihawkEntropius** [comment]
Starting 1:29 https://www.youtube.com/watch?v=XRrbn0wDf-0 there's 3 demons spawning from the portal on retail. 

What happens when you start the escort here is 9 demons spawn and attack at the 2nd pylon. 

The info of the NPC that spawn at 2nd Pilon is :
13:00:17]Selected: Legion Shocktrooper
[13:00:17]Entry: 20402
[13:00:17]DisplayId: 1912 (Native: 1912).
[13:00:17]Unit Flags: 0. Unit Flags 2: 0.
[13:00:17]NPC Flags: 0.
[13:00:17]Dynamic Flags: 4.
[13:00:17]Faction Template: 16.


Quest ID: 10310 
Necessary to do pre quest 10311 to start it.

**Comment by MihawkEntropius** [comment]
tested fixed
