### ISSUE TITLE
Dark Runes

### ISSUE THREAD

**Issue by statsone** [Nextcalibur/Bugtracker#645]
Hi, I've check on wowhead where to get them Dark Runes. Area in EPL Corin's Crossing has NPC's that are supposed to drop them, but after 30min of farming and having various rare/green item drops. Dark Runes are nowhere to be found.
Can you please check the lootable for them because it's the only non-instance farmable spot. 

Also, first time using github, so idk if I'm supposed to add some tags or how it goes. Let me know either way. Thanks

**Comment by Nextcalibur** [comment]
Can you list some of the NPCs you were killing?

**Comment by MihawkEntropius** [comment]
Hello Statsone, 


Thank you for take your time to create a Github accounts and reporting a bug. 

This report is invalid and allow me to suggest you dont use wowhead.com drop rates as factual for TBC, in this case it is not correct. 

https://www.wowhead.com/item=20520/dark-rune Show Dark Runes dropping from EPL npc-s but that is because of later updates, data from wowhead.com comments can be taken as evidence is marked as posted before 3.0.1 patch (pre wotlk comments). 

Actual drop rate in tbc is approximately : https://tbcdb.com/?item=20520

Dark Runes only drop from Scholomance in TBC. 

Another source of TBC data could be but is not always accurate https://classic.wowhead.com/item=20520/dark-rune
